# to build 3hdeng/laverna:4.7 
#FROM node:4.7
FROM 3hdeng/nodejs:4.7 

#RUN npm install -g node-sass 
#RUN npm install -g bower gulp gulp-cli && \
#    echo '{ "allow_root": true }' > /root/.bowerrc
#RUN apt-get update && DEBIAN_FRONTEND=noninteractive && \
#  apt-get install -y  vim


#============================
RUN npm install -g electron-packager


CMD []

